apiVersion: v1 
kind: Service 
metadata: 
 name: mongodb 
 namespace: roboshop 
spec: 
 type: {{ .Values.service.type }} 
 selector: 
  project: roboshop 
  component: mongodb 
  tier: db
 ports: 
  - protocol: TCP 
    port: {{ .Values.service.servicePort }} # service port
    targetPort: 27017 # container port 

---

apiVersion: v1 
kind: Service 
metadata: 
 name: mongodb-headless
 namespace: roboshop 
spec: 
 clusterIP: None
 selector: 
  project: roboshop 
  component: mongodb 
  tier: db
 ports: 
  - protocol: TCP 
    port: {{ .Values.service.servicePort }} # service port
    targetPort: 27017 # container port

