apiVersion: v1 
kind: Service 
metadata: 
 name: mysql 
 namespace: roboshop 
spec:
 type: {{ .Values.service.type }} 
 selector: 
  project: roboshop 
  component: mysql 
  tier: db
 ports: 
  - protocol: TCP 
    port: {{ .Values.service.servicePort }} # service port
    targetPort: 3306 # container port 

--- 
apiVersion: v1 
kind: Service 
metadata: 
 name: mysql-headless
 namespace: roboshop 
spec: 
 clusterIP: None
 selector: 
  project: roboshop 
  component: mysql 
  tier: db
 ports: 
  - protocol: TCP 
    port: {{ .Values.service.servicePort }} # service port
    targetPort: 3306 # container port

--- 

# SC is created by admins
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-ebs 
reclaimPolicy: Retain 
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer