apiVersion: v2  #previosuly v1 now upgraded to v2 
name: mongodb #Chart name
version: 1.0.0 # chart version 
description: mongodb installation #chart description 
appVersion: v1 # this is application version