apiVersion: v2  #previosuly v1 now upgraded to v2 
name: redis #Chart name
version: 1.0.0 # chart version 
description: redis installation #chart description 
appVersion: v1 # this is application version